---
- name: Repo Zabbix - Ubuntu
  apt:
    deb: 'http://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb'
    update_cache: yes

- name: Update apt-get
  apt: update_cache=yes

- name: Instala pacotes Zabbix
  apt: 
    name: 
    - zabbix-agent
    - zabbix-sender
    - zabbix-get
    state: present

- name: Aplica arquivo de configuracao Zabbix Agent
  tags: setupconfig
  template:
    src: templates/zabbix_agentd_ubuntu.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: zabbix
    group: zabbix
    mode: 0644

- name: Altera permiss√£o Zabbix
  tags: setupconfig
  file:
    path: /etc/zabbix/
    mode: 0775
    owner: zabbix
    group: zabbix

- name: Habilita e inicia servico do Linux
  tags: setupconfig
  service:
    name: zabbix-agent
    enabled: yes
    state: started