---

## Variaveis de vers√£o
zabbix_proxy_version: 6.0
zabbix_proxy_version_minor: 1
zabbix_version: "{{ zabbix_proxy_version }}"

## Repositorio do Zabbix
zabbix_repo: 'https://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/{{ansible_distribution_major_version}}/x86_64/zabbix-release-{{ zabbix_version }}-{{ zabbix_proxy_version_minor }}.el{{ansible_distribution_major_version}}.noarch.rpm'

## Banco de dados escolhido
#zabbix_proxy_database: mysql
#zabbix_proxy_database_long: mysql
#zabbix_proxy_database: pgsql
#zabbix_proxy_database_long: postgresql
zabbix_proxy_database: sqlite3
zabbix_proxy_database_long: sqlite3

## Variaveis para banco de dados
zabbix_proxy_dbname: zabbix_proxy
zabbix_database_creation: true
zabbix_proxy_dbpassword: zabbix_proxy