---

zabbix_proxy_version: 6.0-1
zabbix_version: "{{ zabbix_proxy_version }}"

zabbix_repo:  'https://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/{{ansible_distribution_major_version}}/x86_64/zabbix-release-{{ zabbix_version }}.el{{ansible_distribution_major_version}}.noarch.rpm'