  - name: Desabilitando o SELinux
    selinux:
     state: disabled

  - name: Instalando o pacote do zabbix no {{ansible_distribution}}-{{ansible_distribution_major_version}}
    dnf:
      disable_gpg_check: yes
      name: 'https://repo.zabbix.com/zabbix/6.0/rhel/{{ansible_distribution_major_version}}/x86_64/zabbix-release-6.0-1.el8.noarch.rpm'
      state: present

  - name: Instalando Zabbix Agent 2 no {{ansible_distribution}}-{{ansible_distribution_major_version}}
    dnf:
     name: zabbix-agent
     enablerepo: zabbix
     update_cache: true
     state: latest
